import { Link } from 'react-router-dom';
import { ArrowUpRight, Database, LockKeyhole, RefreshCw, ShieldAlert } from 'lucide-react';
import useData from '../hooks/useData.js';
import { getAgents, getPolicies, getResources } from '../services/catalog.js';
import { Stagger, StaggerItem } from '../components/motion/Stagger.jsx';
import { AgentAvatar, Button, ErrorState, LoadingState, PageHeader } from '../components/ui.jsx';

export default function Policies() {
  const query = useData(async (options) => { const [agents, policies, resources] = await Promise.all([getAgents(options), getPolicies(options), getResources(options)]); return { agents, policies, resources }; });
  return <>
    <PageHeader eyebrow="THE RULES BEHIND THE GATE" title="Policies & Agents" description="Inspect each agent’s scope and the organization rules that govern every proposed action."><Button onClick={query.reload}><RefreshCw size={13} /> Refresh</Button><Link className="btn" to="/playground">Test a proposal <ArrowUpRight size={13} /></Link></PageHeader>
    <div className="mb-7 grid gap-3 sm:grid-cols-3">{[{ range: '75–100', label: 'TRUSTED', detail: 'Simulated execution', color: 'text-trusted' }, { range: '40–74', label: 'SUSPICIOUS', detail: 'Human approval required', color: 'text-suspicious' }, { range: '0–39', label: 'UNSAFE', detail: 'Execution blocked', color: 'text-unsafe' }].map((item) => <div key={item.label} className="glass-card flex items-center justify-between p-4"><div><p className={`font-mono text-[10px] ${item.color}`}>{item.label}</p><p className="mt-2 text-[10px] text-muted">{item.detail}</p></div><span className={`font-mono text-xl ${item.color}`}>{item.range}</span></div>)}</div>
    <p className="mb-7 flex items-center gap-2 font-mono text-[10px] leading-6 text-blocked"><ShieldAlert size={14} className="shrink-0" /> HARD BLOCK — overrides score. Permissions and critical policies cannot be approved away.</p>
    {query.loading ? <LoadingState /> : query.error ? <ErrorState error={query.error} retry={query.reload} /> : <>
      <div className="mb-4 flex items-center justify-between"><h2 className="text-lg">Registered agents</h2><span className="eyebrow text-[9px]!">{query.data.agents.length} AGENTS</span></div><Stagger className="mb-8 grid gap-4 md:grid-cols-3">{query.data.agents.map((agent) => <StaggerItem key={agent.key} className="glass-card p-5"><div className="flex items-center gap-3"><AgentAvatar agent={agent} /><h3 className="text-base">{agent.name}</h3></div><p className="mt-4 min-h-14 text-[11px] leading-6 text-muted">{agent.description}</p><p className="eyebrow mt-5 mb-3 text-[8px]!">ALLOWED TOOLS</p><div className="flex flex-wrap gap-1.5">{agent.allowedTools.map((tool) => <span key={tool} className="badge badge-neutral text-[9px]!">{tool}</span>)}</div><p className="eyebrow mt-5 mb-3 text-[8px]!">DATA ACCESS</p><div className="flex flex-wrap gap-1.5">{agent.allowedDataClasses.map((dataClass) => <span key={dataClass} className="badge badge-neutral text-[9px]!">{dataClass}</span>)}</div></StaggerItem>)}</Stagger>
      <div className="mb-4 flex items-center justify-between"><h2 className="text-lg">Organization policies</h2><span className="eyebrow text-[9px]!">READ-ONLY CATALOG</span></div><section className="glass-card mb-8 divide-y divide-line">{query.data.policies.map((policy) => <div key={policy.key} className="flex flex-wrap items-start gap-4 p-5"><div className={`rounded-lg border p-2.5 ${policy.severity === 'hard_block' ? 'border-blocked/20 bg-blocked/5 text-blocked' : 'border-line text-muted'}`}><LockKeyhole size={17} /></div><div className="min-w-0 flex-1"><h3 className="text-[14px]">{policy.name}</h3><p className="mt-1 text-[11px] leading-6 text-muted">{policy.description}</p><p className="mt-2 font-mono text-[9px] text-muted">{policy.key}</p></div><div className="flex flex-col items-end gap-2"><span className={`badge ${policy.severity === 'hard_block' ? 'badge-blocked' : 'badge-suspicious'}`}>{policy.severity === 'hard_block' ? 'HARD BLOCK' : `−${policy.penalty} POINTS`}</span><span className={`font-mono text-[8px] ${policy.enabled ? 'text-trusted' : 'text-muted'}`}>{policy.enabled ? '● ENABLED' : '○ DISABLED'}</span></div></div>)}</section>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-lg"><Database size={17} className="text-muted" /> Resource directory</h2><span className="eyebrow text-[8px]!">METADATA ONLY · CONTENT STAYS ON THE SERVER</span></div><section className="glass-card overflow-x-auto"><table className="data-table min-w-[550px]"><thead><tr><th>Resource</th><th>Data class</th><th>Records</th></tr></thead><tbody>{query.data.resources.map((resource) => <tr key={resource.key}><td><p>{resource.name}</p><p className="mt-1 font-mono text-[9px] text-muted">{resource.key}</p></td><td><span className="badge badge-neutral">{resource.dataClass}</span></td><td className="font-mono">{resource.recordCount}</td></tr>)}</tbody></table></section>
    </>}
  </>;
}
